# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

name: "Component CI: Library Uniqueness"

on:
  workflow_call:
    inputs:
      docker_image:
        type: string
        required: true
      linux_runner:
        type: string
        required: true

permissions:
  contents: read

jobs:
  linux:
    name: Linux
    runs-on: ${{ inputs.linux_runner }}
    container:
      image: ${{ inputs.docker_image }}
    defaults:
      run:
        shell: bash
        working-directory: projects/hipblaslt/tensilelite
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install tox
        run: python -m pip install tox

      - name: Run Library Uniqueness gate
        run: python -m tox -e library-uniqueness
